site_name: Relatórios
repo_url: "https://gitlab.com/lappis-unb/decidimbr/ecossistemasl/-/blob/160-geracao-de-relatorio-automatico-com-jupyter-notebooks/relat%C3%B3rios/conjuv/relatorio_conjuv.md?ref_type=heads" 

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - toc.integrate
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# https://squidfunk.github.io/mkdocs-material/customization/
extra_css:
  - styles/extra.css

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Relatórios: 'relatorio_conjuv.md'