site_name: Pacote Conferência BP
repo_url: "https://gitlab.com/lappis-unb/decidimbr/documentacao/-/blob/master/conjuv/relatorio_conjuv.md?ref_type=heads" 

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - toc.integrate
    - content.tabs.link
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  extra:
    social:
      - icon: fontawesome/brands/gitlab
        link: https://gitlab.com/lappis-unb/decidimbr

# https://squidfunk.github.io/mkdocs-material/customization/
extra_css:
  - styles/extra.css

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: 'index.md'
  - 'Hello world':
     - 'Hello Mundo': 'tutoriais/Colegiados/HelloWorld10.md'
  - 'Pacote Conferência': 
     - 'Conferência no BP': 'PacoteConferencia/conferencias.md'
     - 'Responsabilidades': 'PacoteConferencia/responsabilidades.md'
     - 'Moderação': 'PacoteConferencia/moderacao.md'
     - 'Jornada da Presidência': 'tutoriais/Conferencias/jornadadapresidencia.md'
     - 'Jornada da Comissão Organizadora': 'tutoriais/Conferencias/jornadacomissaoorg.md'
     - 'Jornada do Usuário Cidadão': 'tutoriais/Conferencias/JornadaUsuarioCidadao.md'
     - 'Jornada da Comissão Organizadora - MMA': 'tutoriais/Conferencias/JornadaCriarReuniaoouConferencia.md'

  - 'Consulta Pública':
    - 'Jornada da Presidência': 'ConsultasPublicas/JornadaPresidencia.md'
    - 'Jornada do Órgão': 'ConsultasPublicas/JornadadoOrgao.md'
  
  - 'Gestão Espaços Participativos':
    - 'Sumário de Documentações': 'tutoriais/sumario.md'
    - 'Audiências Públicas':
      - 'Jornada da Presidência': 'tutoriais/AudienciasPublicas/JornadaPresidencia.md'
      - 'Jornada do Órgão': 'tutoriais/AudienciasPublicas/JornadaOrgao.md'
    - 'Colegiados': 
      - 'Jornada da Presidência': 'tutoriais/Colegiados/JornadaPresidencia.md'
      - 'Jornada do Órgão': 'tutoriais/Colegiados/JornadaOrgao.md'   
    - 'Consultas Públicas': 
      - 'Jornada da Presidência': 'tutoriais/ConsultasPublicas/JornadaPresidencia.md'
      - 'Jornada do Órgão': 'tutoriais/ConsultasPublicas/JornadaOrgao.md'
    - 'Questionário Perfil': 
      - 'Jornada da Presidência': 'tutoriais/QuestionarioPerfil/JornadaPresidencia.md'
      - 'Jornada do Órgão': 'tutoriais/QuestionarioPerfil/JornadaOrgao.md'
    - 'Gestão de Propostas': 'propostas.md'
    
  - 'Exemplos de Relatorios  Automatizados':
    - 'Relatorios Semanais Conjuv':
      - 'Relatório 13/09': 'PacoteConferencia/conjuv/relatorio_13-09/relatorio_conjuv-13-09.md'
      - 'Relatório 27/09': 'PacoteConferencia/conjuv/relatorio_27-09/relatorio_conjuv-27-09.md'
      - 'Relatório 03/10': 'PacoteConferencia/conjuv/relatorio_03-10/relatorio_conjuv_03-10.md'
      - 'Relatório 05/10': 'PacoteConferencia/conjuv/relatorio_03-10/relatorio_conjuv_03-10.md'
      - 'Relatório 11/10': 'PacoteConferencia/conjuv/relatorio_11-10/relatorio_conjuv_11-10.md'
      - 'Relatório 17/10': 'PacoteConferencia/conjuv/relatorio_17-10/relatorio_conjuv_17-10.md'
      - 'Relatório 23/10': 'PacoteConferencia/conjuv/relatorio_23-10/relatorio_conjuv_23-10.md'
      - 'Relatório 31/10': 'PacoteConferencia/conjuv/relatorio_31-10/relatorio_conjuv_31-10.md'
    - 'Relatório ENGD': 'engd/relatorio.md'









