site_name: Autenticação secundária - Brasil Participativo

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# https://squidfunk.github.io/mkdocs-material/customization/
extra_css:
  - styles/extra.css

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Visão Geral: 'index.md'
  - Módulos Decidim: 'modulos.md'
  - Keycloak: 'keycloak.md'
  - Devise: 'devise.md'
